name: deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533266989803:role/sftp-github-role
          role-session-name: github-session
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        env:
          TF_VAR_region: us-east-1

      - name: Upload tfplan to S3
        run: |
          aws s3 cp tfplan s3://my-s3-bucket1111/tfplan
        env:
          AWS_REGION: us-east-1

  apply:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533266989803:role/sftp-github-role
          role-session-name: github-session
          aws-region: us-east-1

      - name: Download tfplan from S3
        run: |
          aws s3 cp s3://my-s3-bucket1111/tfplan tfplan
        env:
          AWS_REGION: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.6

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply tfplan
        env:
          TF_VAR_region: us-east-1
